### ISSUE TITLE
Question on Calibration Board Pattern

### ISSUE THREAD

**Issue by dejongyeong** [tudelft-iv/multi_sensor_calibration#10]
Hi Guys,

The sensors that were used are mono camera, lidar and radar. I would like to ask about is the proposed pattern be used for mono camera and would like to ask about the size of the trihedral corner reflector.

Thanks.

**Comment by RonaldEnsing** [comment]
More info on the calibration board can be found here: https://github.com/tudelft-iv/multi_sensor_calibration/blob/master/docs/calibration_board.md

Does this answer your question about the trihedral reflector: https://github.com/tudelft-iv/multi_sensor_calibration/issues/2 ?

**Comment by dejongyeong** [comment]
Hi @RonaldEnsing, Thanks for getting back to me.

Which means for the board pattern, I doesn't have to incorporate a checkerboard pattern into the current board pattern right?

Thanks for the link to the question about the trihedral reflector. Just wondering what radar sensor did you used on this? Currently, we are using SmartMicro Automotive UMRR T-153 radar.

Thanks.

**Comment by frankeverdij** [comment]
Hello dejongyeong,
The radar used is also mentioned in issue #2

**Comment by RonaldEnsing** [comment]
You do not need to include a chessboard pattern like this [1] if that is what you mean.

[1] https://docs.opencv.org/2.4/doc/tutorials/calib3d/camera_calibration/camera_calibration.html#results

**Comment by dejongyeong** [comment]
@RonaldEnsing @frankeverdij Thanks for the response. Much appreciated!!!
