### ISSUE TITLE
Query: Temporal Synchronization

### ISSUE THREAD

**Issue by dejongyeong** [tudelft-iv/multi_sensor_calibration#26]
Hi 👋 I was wondering from your previous experience, does the published topics from the sensors drivers in ROS went through message filter approximate synchronization before accumulating the data for extrinsic calibration?

Thanks.

**Comment by RonaldEnsing** [comment]
The assumption is a static environment. The accumulator does not take time stamps into account.

**Comment by dejongyeong** [comment]
@RonaldEnsing correct me if i'm wrong, does the static environment that you mentioned refers to that the board is static when accumulating the data? Thanks.

**Comment by RonaldEnsing** [comment]
Yes, that is what I mean.

**Comment by dejongyeong** [comment]
@RonaldEnsing thanks 😊
