### ISSUE TITLE
raw radar data loading

### ISSUE THREAD

**Issue by ixtiyoruz** [tudelft-iv/multi_sensor_calibration#7]
Hi, thank you for your open-source. 
(I am new in the field of Radar and multi Sensor calibration). I have one question. I assume that you first recorded images, radar information, and lidar information simultaneously and stored them. I found in the optimization package you are reading detected points from CSV files. However, I couldn't find a clue to raw radar data. So, I wonder how are you reading it, where the raw radar data should be stored?

**Comment by EaiPool** [comment]
Hey,

In case you're still on this: you should use the radar detector to extract the calibration board detections. The data of these detections is what gets stored in the CSV files. 
Depending on what you mean by "raw radar data", you should either create a ROS node to convert into the format used by the radar detector, or write something which uses the non-ROS radar detection backend to extract correct detections from your raw data.

**Comment by ixtiyoruz** [comment]
Hi, thank you for your response. I wrote the question out of poor knowledge, however now I have a clue of what to do. Than you very much.
