### ISSUE TITLE
lidar_detector_node pcl warning

### ISSUE THREAD

**Issue by MI-Hussain** [tudelft-iv/multi_sensor_calibration#8]
hi. 
we made the calibration board according to the same dimension as given in code. But we are getting the following error as attached in files...  we are using **"velodyne-32 channel"**  

In the lidar_detector_node giving us the following error. 

"ring too small"

and nothing is showing in the topic is publishing by this detector

![ring too small](https://user-images.githubusercontent.com/44750142/71304773-45f44580-240e-11ea-90f6-877786e82fa6.png)

In the mono_detector_node giving us the following exception

![mon_dtector_error](https://user-images.githubusercontent.com/44750142/71304778-4e4c8080-240e-11ea-804f-0c39a35134e1.png)
"Number of circles found: '0', but should be exactly 4."

your help is requested please...

If we put the calibration board with very close within 1m distance to car, then the circles found . If we put the board little far as according to your paper 5m distance then its not detecting the circles.

**Comment by dejongyeong** [comment]
@ishfaq-gist  I came across the same issue on ring too small. Would like to know what is the issue of that? Thanks.

**Comment by MI-Hussain** [comment]
@dejongyeong I think the problem will be solved if you try to change the location of the calibration board from the vehicle (I think now your board is far from the sensor  e.g more than 5m)  or your circles front and backside is different than the desired.
